---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: chef/centos-6.5
    driver_config:
       network: 
        - ["forwarded_port", {guest: 80, host: 9080}]

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
